// Web App Manifest. Next 16 file convention — `app/manifest.ts` exporting
// a default function returning a MetadataRoute.Manifest object. Next emits
// it at /manifest.webmanifest. Icons reference the programmatic
// app/icon.tsx and app/apple-icon.tsx routes plus the existing static SVG
// fallback so PWA installers always have something to draw.

import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Voyage",
    short_name: "Voyage",
    description:
      "Plan your whole trip in one place — flights, hotels, day-by-day schedule, and on-the-go nearby food & coffee.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    background_color: "#050507",
    theme_color: "#050507",
    orientation: "portrait",
    categories: ["travel", "lifestyle", "productivity"],
    icons: [
      // Static SVG — scales to any size, used by manifest readers that
      // prefer vector. Listed twice so Android adaptive icons get a
      // maskable copy without distorting the "any" entry.
      {
        src: "/icon.svg",
        sizes: "any",
        type: "image/svg+xml",
        purpose: "any",
      },
      {
        src: "/icon.svg",
        sizes: "any",
        type: "image/svg+xml",
        purpose: "maskable",
      },
      // Generated by app/icon.tsx — Next gives this stable URL.
      {
        src: "/icon",
        sizes: "32x32",
        type: "image/png",
        purpose: "any",
      },
      // Generated by app/apple-icon.tsx — iOS home-screen icon.
      {
        src: "/apple-icon",
        sizes: "180x180",
        type: "image/png",
        purpose: "any",
      },
    ],
    shortcuts: [
      {
        name: "Plan a trip",
        short_name: "Plan",
        url: "/plan",
      },
      {
        name: "My trips",
        short_name: "Trips",
        url: "/trips",
      },
      {
        name: "Trip wallet",
        short_name: "Wallet",
        url: "/wallet",
      },
    ],
  };
}
